[package]
name = "async-video"
version = "0.1.0"
authors = ["post-rex <post-rex@pm.me>"]
edition = "2018"

[dependencies]
actix = "0.10"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
serde = { version = "1.0.120", features =  ["derive"] }
serde_json = "1.0.61"
rand = "0.8.2"